version: "3.3"

services:
  api:
    container_name: schedule-api
    image: node:12
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - base
    ports:
      - 3000:3000
    volumes:
      - ./api/:/app
    env_file:
      - envs/.api.env
    depends_on:
      - db

  front:
    container_name: schedule-front
    image: node:12
    command: sh -c "npm install && npm start"
    working_dir: /app
    ports:
      - 80:80
    env_file:
      - envs/.frontend.env
    volumes:
      - ./client/:/app

  db:
    container_name: db_schedule
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .data/db:/data/db
    networks:
      - base
    env_file:
      - envs/.api.env

networks:
  base:

volumes:
  db:
